query session {
  getSession {
    cacheId
    favoritePickup {
      cacheId
      name
      address {
        addressId
        complement
        country
        geoCoordinates
        neighborhood
        number
        postalCode
        state
        street
      }
    }
  }
}
