query SkuPickupSLAs(
  $itemId: String
  $seller: String
  $lat: String
  $long: String
  $country: String
) {
  skuPickupSLAs(
    itemId: $itemId
    seller: $seller
    long: $long
    lat: $lat
    country: $country
  ) {
    id
    shippingEstimate
    pickupStoreInfo {
      friendlyName
      address {
        street
        number
        cacheId
        addressId
        complement
        neighborhood
        country
        state
        geoCoordinates
        postalCode
        city
      }
    }
  }
}
